'use client';

import React, { useState } from 'react';
import GovtHeader from '@/components/GovtHeader';
import Sidebar from '@/components/Sidebar';
import Footer from '@/components/Footer';
import Breadcrumbs from '@/components/Breadcrumbs';
import NoticeBanner from '@/components/NoticeBanner';
import UploadModal from '@/components/UploadModal';

export default function ReasoningEnginePage() {
  const [isUploading, setIsUploading] = useState(false);
  const [expandedStep, setExpandedStep] = useState<number | null>(4);

  const steps = [
    {
      id: 1,
      title: '1. Spatial Bounding & Geodetic Alignment',
      subtitle: 'Resolved user natural language query to closed bounding polygon in EPSG:4326',
      duration: '120ms',
      status: 'COMPLETED',
      statusColor: 'bg-emerald-100 text-emerald-800 border-emerald-300',
      details:
        'Parsed input coordinates [14.82°N, 73.91°E] to [15.45°N, 74.52°E]. Matched against Survey of India admin boundary shapefile v2.1.',
    },
    {
      id: 2,
      title: '2. Multi-Sensor Telemetry Downlink Ingestion',
      subtitle: 'Retrieved multi-spectral optical and SAR radar telemetry feeds from NRSC cache',
      duration: '340ms',
      status: 'COMPLETED',
      statusColor: 'bg-emerald-100 text-emerald-800 border-emerald-300',
      details:
        'Feeds ingested: Cartosat-3 Panchromatic (0.35m) and RISAT-1A C-band SAR (1m). Radiometric headers validated.',
    },
    {
      id: 3,
      title: '3. Cloud Masking & Radiometric Calibration',
      subtitle: 'Filtered atmospheric disturbance and compute Top-Of-Atmosphere reflectance',
      duration: '210ms',
      status: 'COMPLETED',
      statusColor: 'bg-emerald-100 text-emerald-800 border-emerald-300',
      details:
        'Cloud cover 2.4% masked out using band-quality QA raster. SAR C-band penetration used for cloud-covered pixels.',
    },
    {
      id: 4,
      title: '4. Multi-Temporal Vegetation Index (NDVI) Differential',
      subtitle: 'Executed matrix subtraction between Nov 2022 baseline and Feb 2026 satellite pass',
      duration: '480ms',
      status: 'COMPLETED',
      statusColor: 'bg-emerald-100 text-emerald-800 border-emerald-300',
      details:
        'Computed ΔNDVI = (NIR - RED) / (NIR + RED). Identified 142.8 Hectares of canopy density reduction (-8.4%) in Sector B-4.',
    },
    {
      id: 5,
      title: '5. Cryptographic Verification & Evidence Package',
      subtitle: 'Generated signed PDF audit trail compliant with Digital India data standards',
      duration: '90ms',
      status: 'COMPLETED',
      statusColor: 'bg-emerald-100 text-emerald-800 border-emerald-300',
      details:
        'Signed with SHA-256 HMAC key: 0x9f8b...7a2d. Ready for submission to Ministry of Environment & Forests (MoEFCC).',
    },
  ];

  return (
    <div className="min-h-screen flex flex-col bg-background text-on-background">
      <GovtHeader onOpenUpload={() => setIsUploading(true)} />
      <Breadcrumbs currentTitle="Reasoning Engine" />

      <div className="flex flex-1">
        <Sidebar />

        <main className="flex-1 p-4 md:p-8 max-w-7xl mx-auto space-y-6">
          <NoticeBanner
            title="Algorithmic Evidence & Reasoning Notice"
            message="Reasoning traces generated by SAT AI undergo mathematical validation and cryptographic signing to ensure full compliance with RTI and Digital India audit guidelines."
            type="verified"
          />

          {/* Header */}
          <div>
            <h1 className="text-2xl sm:text-3xl font-extrabold text-on-surface">
              Evidence Planning & Reasoning Execution Graph
            </h1>
            <p className="text-xs text-on-surface-variant mt-1">
              Inspect step-by-step LLM decomposition, satellite telemetry downlinks, and mathematical operations producing verified spatial evidence.
            </p>
          </div>

          {/* Goal Summary Card */}
          <div className="bg-primary-container text-white p-5 rounded-xl shadow-md flex flex-col md:flex-row md:items-center justify-between gap-4">
            <div className="space-y-1">
              <span className="text-[10px] uppercase font-bold tracking-wider text-secondary-fixed bg-white/10 px-2 py-0.5 rounded">
                Active Reasoning Goal
              </span>
              <h2 className="text-base sm:text-lg font-bold">
                &ldquo;Evaluate deforestation and canopy density change in Western Ghats Biosphere&rdquo;
              </h2>
              <p className="text-xs text-gray-300">
                Target Bounds: 14.82°N to 15.45°N • Target Dates: Nov 2022 vs. Feb 2026
              </p>
            </div>

            <div className="flex items-center gap-4 bg-white/10 p-3 rounded-lg border border-white/10">
              <div className="text-center">
                <p className="text-[10px] text-gray-300 uppercase">Confidence</p>
                <p className="text-xl font-extrabold text-emerald-400">98.6%</p>
              </div>
              <div className="h-8 w-[1px] bg-white/20"></div>
              <div className="text-center">
                <p className="text-[10px] text-gray-300 uppercase">Total Time</p>
                <p className="text-xl font-extrabold text-white">1.24s</p>
              </div>
            </div>
          </div>

          {/* Decomposition Tree */}
          <div className="space-y-4">
            <h2 className="font-bold text-sm text-on-surface flex items-center gap-2">
              <span className="material-symbols-outlined text-secondary">account_tree</span>
              <span>Algorithmic Execution Steps & Reasoning Nodes</span>
            </h2>

            <div className="space-y-3">
              {steps.map((step) => {
                const isExpanded = expandedStep === step.id;
                return (
                  <div
                    key={step.id}
                    className="bg-surface-container-lowest border border-outline-variant/60 rounded-xl overflow-hidden shadow-xs transition-all"
                  >
                    <div
                      onClick={() => setExpandedStep(isExpanded ? null : step.id)}
                      className="p-4 flex items-center justify-between cursor-pointer hover:bg-surface-container-low/50 transition-colors"
                    >
                      <div className="flex items-center space-x-3">
                        <div className="w-8 h-8 rounded-full bg-secondary-fixed text-on-secondary-fixed flex items-center justify-center font-bold text-xs">
                          {step.id}
                        </div>
                        <div>
                          <h3 className="font-bold text-xs sm:text-sm text-on-surface">{step.title}</h3>
                          <p className="text-[11px] text-on-surface-variant">{step.subtitle}</p>
                        </div>
                      </div>

                      <div className="flex items-center space-x-3">
                        <span className={`text-[10px] font-bold px-2 py-0.5 rounded ${step.statusColor}`}>
                          {step.status}
                        </span>
                        <span className="text-xs font-mono text-on-surface-variant">{step.duration}</span>
                        <span className="material-symbols-outlined text-on-surface-variant text-base">
                          {isExpanded ? 'expand_less' : 'expand_more'}
                        </span>
                      </div>
                    </div>

                    {isExpanded && (
                      <div className="p-4 bg-surface-container-low border-t border-outline-variant/40 space-y-3 text-xs">
                        <div className="p-3 bg-surface-container-lowest rounded-lg border border-outline-variant/40 font-mono text-on-surface">
                          <p className="text-[11px] text-on-surface-variant mb-1 font-sans font-bold">
                            Detailed Node Output:
                          </p>
                          {step.details}
                        </div>
                        <div className="flex items-center justify-between text-[11px] text-on-surface-variant font-mono">
                          <span>Verified Node Key: 0x8f...4b</span>
                          <span className="text-emerald-700 font-bold">✓ Compliance Check Passed</span>
                        </div>
                      </div>
                    )}
                  </div>
                );
              })}
            </div>
          </div>
        </main>
      </div>

      <Footer />
      <UploadModal isOpen={isUploading} onClose={() => setIsUploading(false)} />
    </div>
  );
}
